### ISSUE TITLE
"Command invocation failed"

### ISSUE THREAD

**Issue by eljojo** [andremedeiros/loon#42]
Hi, I tried to get this running but got stuck at this error. How can I debug?

```
❯ sudo echo "hehe"
hehe
❯ loon up
Command invocation failed:
-------------------- 8< stdout 8< --------------------
-------------------- 8< stderr 8< --------------------
```
```
name: Radiophonic
url: https://github.com/eljojo/radiophonic
deps:
  - mysql
  - redis
  - ruby: 2.6.6
  - node: latest
tasks:
  setup:
    description: Fetches dependencies and runs database migrations
    command: |
      bundle check || bundle install
      rake db:setup
      rake db:migrate
  server:
    description: Starts the web server
    command: bundle exec rails server
  jobs:
    description: Starts the job worker
    command: bundle exec sidekiq
  test:
    description: Runs the test suite
    command: bundle exec rails test
```

if I change my loon file to postgres it shows:
```
❯ loon up
✓ Installing software
⡿ Setting up project networking
⣽ Setting up Node.JS
Command invocation failed:
```
